name: Jobalots Bot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias y navegador
        run: npm install

      - name: Ejecutar bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GIST_ID:         ${{ secrets.GIST_ID }}
          GIST_TOKEN:      ${{ secrets.GIST_TOKEN }}
        run: node bot.js
